package springboot.dao.emailMyISAM.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import springboot.dao.emailMyISAM.model.EmailMyISAM;
import springboot.dao.emailMyISAM.model.EmailMyISAMExample;


public interface EmailMyISAMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    long countByExample(EmailMyISAMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    int deleteByExample(EmailMyISAMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    int deleteByPrimaryKey(Integer email_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    int insert(EmailMyISAM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    int insertSelective(EmailMyISAM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    List<EmailMyISAM> selectByExample(EmailMyISAMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    EmailMyISAM selectByPrimaryKey(Integer email_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") EmailMyISAM record, @Param("example") EmailMyISAMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    int updateByExample(@Param("record") EmailMyISAM record, @Param("example") EmailMyISAMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    int updateByPrimaryKeySelective(EmailMyISAM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    int updateByPrimaryKey(EmailMyISAM record);
}