package springboot.dao.emailMyISAM.model;

import java.util.ArrayList;
import java.util.List;

public class EmailMyISAMExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public EmailMyISAMExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmail_idIsNull() {
            addCriterion("email_id is null");
            return (Criteria) this;
        }

        public Criteria andEmail_idIsNotNull() {
            addCriterion("email_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmail_idEqualTo(Integer value) {
            addCriterion("email_id =", value, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idNotEqualTo(Integer value) {
            addCriterion("email_id <>", value, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idGreaterThan(Integer value) {
            addCriterion("email_id >", value, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("email_id >=", value, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idLessThan(Integer value) {
            addCriterion("email_id <", value, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idLessThanOrEqualTo(Integer value) {
            addCriterion("email_id <=", value, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idIn(List<Integer> values) {
            addCriterion("email_id in", values, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idNotIn(List<Integer> values) {
            addCriterion("email_id not in", values, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idBetween(Integer value1, Integer value2) {
            addCriterion("email_id between", value1, value2, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_idNotBetween(Integer value1, Integer value2) {
            addCriterion("email_id not between", value1, value2, "email_id");
            return (Criteria) this;
        }

        public Criteria andEmail_addressIsNull() {
            addCriterion("email_address is null");
            return (Criteria) this;
        }

        public Criteria andEmail_addressIsNotNull() {
            addCriterion("email_address is not null");
            return (Criteria) this;
        }

        public Criteria andEmail_addressEqualTo(String value) {
            addCriterion("email_address =", value, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressNotEqualTo(String value) {
            addCriterion("email_address <>", value, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressGreaterThan(String value) {
            addCriterion("email_address >", value, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressGreaterThanOrEqualTo(String value) {
            addCriterion("email_address >=", value, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressLessThan(String value) {
            addCriterion("email_address <", value, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressLessThanOrEqualTo(String value) {
            addCriterion("email_address <=", value, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressLike(String value) {
            addCriterion("email_address like", value, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressNotLike(String value) {
            addCriterion("email_address not like", value, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressIn(List<String> values) {
            addCriterion("email_address in", values, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressNotIn(List<String> values) {
            addCriterion("email_address not in", values, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressBetween(String value1, String value2) {
            addCriterion("email_address between", value1, value2, "email_address");
            return (Criteria) this;
        }

        public Criteria andEmail_addressNotBetween(String value1, String value2) {
            addCriterion("email_address not between", value1, value2, "email_address");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table email_myisam
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 22 22:21:38 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table email_myisam
     *
     * @mbg.generated Sun Apr 22 22:21:38 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}