package test.dao;

import springboot.dal.emailMyISAM.EmailMyISAM;

public interface EmailMyISAMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:18:13 CST 2018
     */
    int deleteByPrimaryKey(Integer email_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:18:13 CST 2018
     */
    int insert(EmailMyISAM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:18:13 CST 2018
     */
    int insertSelective(EmailMyISAM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:18:13 CST 2018
     */
    EmailMyISAM selectByPrimaryKey(Integer email_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:18:13 CST 2018
     */
    int updateByPrimaryKeySelective(EmailMyISAM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:18:13 CST 2018
     */
    int updateByPrimaryKey(EmailMyISAM record);
}