package test.dao;

import springboot.dal.emailMyISAM.EmailMyISAMEntity;

public interface EmailMyISAMEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:17:36 CST 2018
     */
    int deleteByPrimaryKey(Integer email_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:17:36 CST 2018
     */
    int insert(EmailMyISAMEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:17:36 CST 2018
     */
    int insertSelective(EmailMyISAMEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:17:36 CST 2018
     */
    EmailMyISAMEntity selectByPrimaryKey(Integer email_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:17:36 CST 2018
     */
    int updateByPrimaryKeySelective(EmailMyISAMEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:17:36 CST 2018
     */
    int updateByPrimaryKey(EmailMyISAMEntity record);
}